---
- name: "Install terminal related packages"
  pacman:
    name:
      - "alacritty"
      - "kitty"
      - "xterm"
    state: "present"
  become: yes

- name: "Create folder for terminal configurations"
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0700"
  with_items:
    - "{{ kitty_directory }}"
    - "{{ kitty_directory }}/scripts"
    - "{{ alacritty_directory }}"

- name: "Copy terminal configurations"
  template:
    src: "{{ item.directory }}/{{ item.file }}.j2"
    dest: "{{ item.destination }}/{{ item.file }}"
    mode: "0600"
  with_items:
    - { destination: "{{ alacritty_directory }}", directory: "alacritty", file: "alacritty.toml" }
    - { destination: "{{ kitty_directory }}", directory: "kitty", file: "kitty.conf" }
    - { destination: "{{ kitty_directory }}", directory: "kitty", file: "colors.conf" }
    - { destination: "{{ kitty_directory }}", directory: "kitty", file: "grab.conf" }
    - { destination: "{{ kitty_directory }}", directory: "kitty", file: "open-actions.conf" }

- name: "Copy kitty scripts configurations"
  template:
    src: "kitty/scripts/{{ item }}.j2"
    dest: "{{ kitty_directory }}/scripts/{{ item }}"
    mode: "0700"
  with_items:
    - "git_sha_hints.py"
    - "toggle-font-size"

- name: "Download kitty_grab repository"
  git:
    repo: "{{ kitty_grab_repo }}"
    dest: "{{ kitty_directory }}/kitty_grab"
    clone: yes
    update: yes
